### ISSUE TITLE
Вынести расчёт за пределы условий

### ISSUE THREAD

**Issue by coursar** [ITParkSergeyKolupaev/01.Sportmaster#1]
https://github.com/ITParkSergeyKolupaev/01.Sportmaster/blob/ef7b72ccc3b77418eb4834726d2ab61f44f31019/src/main/java/re/itpark/SportMasterBonusService.java#L16

Вы дублируете код в каждой ветке условий - не дублируйте, вынесите его отдельно.

**Comment by ITParkSergeyKolupaev** [comment]
@coursar, исправлено в 8ac23483cef4183a2ed5d37cc9ada62a9f37e859
https://github.com/ITParkSergeyKolupaev/01.Sportmaster/blob/921da2fbcadb670966f355a7091ada2e6218e753/src/main/java/ru/itpark/SportMasterBonusService.java#L13

**Comment by coursar** [comment]
Ниже надо было вынести, а не выше.

**Comment by ITParkSergeyKolupaev** [comment]
@coursar Выносить метод ниже нельзя, т.к. bonusMultiplier нужно рассчитывать до if(....).  bonusMultiplier используется в каждой ветке для расчета. 
https://github.com/ITParkSergeyKolupaev/01.Sportmaster/blob/921da2fbcadb670966f355a7091ada2e6218e753/src/main/java/ru/itpark/SportMasterBonusService.java#L13-L20
