### ISSUE TITLE
Расчёт бонуса при нулевой истории

### ISSUE THREAD

**Issue by coursar** [ITParkSergeyKolupaev/01.Sportmaster#3]
Какой результат должен быть для этого теста?
```java
        {
            SportMasterBonusService sportMasterBonusService = new SportMasterBonusService();
            int calculateBonus = sportMasterBonusService.calculateBonus(0, 1_000, 0);
            assertEquals(0, calculateBonus);
        }
```

**Comment by ITParkSergeyKolupaev** [comment]
@coursar , исправлено в 921da2fbcadb670966f355a7091ada2e6218e753
https://github.com/ITParkSergeyKolupaev/01.Sportmaster/blob/921da2fbcadb670966f355a7091ada2e6218e753/src/test/java/ru/itpark/SportMasterBonusServiceTest.java#L27-L29

**Comment by coursar** [comment]
@ITParkSergeyKolupaev, при 1_000 рублей без первоначальной истории бонус должен быть 0 или 50, а не 100.

**Comment by ITParkSergeyKolupaev** [comment]
@coursar, исправлено в 68c30acae197c74e1caf4b140b019a20520332d9
https://github.com/ITParkSergeyKolupaev/01.Sportmaster/blob/b83234af2de6b1431a433bb2ca6c5af6d2f7d727/src/test/java/ru/itpark/SportMasterBonusServiceTest.java#L27-L29
