### ISSUE TITLE
Переименовать package в ru.itpark

### ISSUE THREAD

**Issue by coursar** [ITParkSergeyKolupaev/01.Sportmaster#4]

**Comment by ITParkSergeyKolupaev** [comment]
@coursar, исправлено в 921da2fbcadb670966f355a7091ada2e6218e753
https://github.com/ITParkSergeyKolupaev/01.Sportmaster/blob/921da2fbcadb670966f355a7091ada2e6218e753/src/main/java/ru/itpark/SportMasterBonusService.java#L1
