### ISSUE TITLE
Исправить опечатки в именовании параметров, переменных

### ISSUE THREAD

**Issue by coursar** [ITParkSergeyKolupaev/01.Sportmaster#5]
https://github.com/ITParkSergeyKolupaev/01.Sportmaster/blob/ef7b72ccc3b77418eb4834726d2ab61f44f31019/src/main/java/re/itpark/SportMasterBonusService.java#L4
https://github.com/ITParkSergeyKolupaev/01.Sportmaster/blob/ef7b72ccc3b77418eb4834726d2ab61f44f31019/src/main/java/re/itpark/SportMasterBonusService.java#L11

**Comment by ITParkSergeyKolupaev** [comment]
@coursar, исправлено в 921da2fbcadb670966f355a7091ada2e6218e753
https://github.com/ITParkSergeyKolupaev/01.Sportmaster/blob/921da2fbcadb670966f355a7091ada2e6218e753/src/main/java/ru/itpark/SportMasterBonusService.java#L11
