### ISSUE TITLE
Исправить опечатки в названиях переменных

### ISSUE THREAD

**Issue by coursar** [ITParkSergeyKolupaev/01.Sportmaster#8]
https://github.com/ITParkSergeyKolupaev/01.Sportmaster/blob/921da2fbcadb670966f355a7091ada2e6218e753/src/main/java/ru/itpark/SportMasterBonusService.java#L15

**Comment by coursar** [comment]
@ITParkSergeyKolupaev , если сделали - закрывайте issue или переназначайте на меня.

**Comment by ITParkSergeyKolupaev** [comment]
@coursar, исправлено в 68c30acae197c74e1caf4b140b019a20520332d9 https://github.com/ITParkSergeyKolupaev/01.Sportmaster/blob/68c30acae197c74e1caf4b140b019a20520332d9/src/main/java/ru/itpark/SportMasterBonusService.java#L16
